-- Shared identity tables that every domain schema links back to via FK.
-- Do NOT duplicate student/staff identity fields inside domain schemas —
-- reference these tables instead.
--
-- NOTE: The original create table statements for public.students and public.staff
-- that were here have been REMOVED because 0013_baseline_reconciliation.sql
-- contains the corrected, fuller versions of both tables (with school_id,
-- admission_number, auth_user_id, etc.) that match the live DB. Applying both
-- would cause a "relation already exists" collision on a fresh database.
