-- ============================================================================
-- 0013_baseline_reconciliation.sql (renumbered from a draft "0009" name — that
-- number is already taken twice in this repo: root 0001-0012 sequence, AND a
-- separate app/supabase/migrations/0009_auth_linkage.sql. This file must be
-- 0013, applied AFTER 0012, not 0009.)
--
-- WHY THIS FILE EXISTS:
-- While exporting the finance schema (0002 fix), a much bigger drift problem
-- was found: most of the live database was never captured in any tracked
-- migration at all — not just finance. Checked via
-- supabase_migrations.schema_migrations.statements (the CLI's own record of
-- what actually ran), not assumptions:
--
--   - public.schools, public.parent_links, public.notifications,
--     public.staff_attendance — never in any migration.
--   - academic.announcements, academic.assignments, academic.grades,
--     academic.lesson_resources, academic.submissions — never in any migration.
--   - communications.messages (the entire messaging feature) — never in any
--     migration.
--   - audit.log table + audit.log_change() function, public.set_updated_at()
--     function, and the 3 enum types (payment_method/payment_status/
--     payout_status) — never in any migration.
--   - public.students / public.staff — ARE tracked (0001), but the tracked
--     version has ~4 columns each. Live has 7-9 columns each (school_id,
--     auth_user_id, admission_number, bank_account_last4, monthly_salary,
--     max_periods, etc.) — none of that is in any migration.
--   - 0004_staff_schema.sql is tracked as "applied" but creates a `staff`
--     schema + staff.leave_requests table that DOES NOT EXIST live at all —
--     confirmed via pg_namespace lookup. It's a dead/orphaned migration.
--     Live has public.leave_requests instead, which is captured below.
--     Recommend deleting or renaming 0004 in the repo since it doesn't
--     reflect reality and would confuse a fresh apply.
--
-- Generated by reading the LIVE Supabase project (yhcyhwpdgqupylrnkqht) via
-- information_schema / pg_catalog on 2026-07-25 — not reconstructed from
-- memory. Companion file to 0002_finance_schema.sql (finance-only export from
-- earlier the same session).
--
-- ORDER: This repo's real migrations run 0001-0012 (0002 being the finance
-- stub this session replaces). Apply this file LAST, as 0013 — after 0012,
-- not where a "0009" name might suggest. Also note: 0009_auth_linkage.sql
-- currently lives at app/supabase/migrations/ (nested, wrong location) rather
-- than the root supabase/migrations/ — confirm it's been applied and/or move
-- it into the real sequence before relying on migration order end-to-end.
--
-- ONE HISTORICAL ODDITY, not fixed here — flagging only: public.staff has TWO
-- functionally-identical FK constraints on school_id (`employees_school_id_fkey`
-- and `fk_employees_school`), and its auto-generated constraint names still say
-- "employees_" (e.g. employees_pkey) — clear evidence the table was renamed
-- from `employees` to `staff` at some point without renaming its constraints.
-- Harmless, but this file creates only ONE fk (can't have two identical ones).
-- ============================================================================


-- ============================================================================
-- Enum types — CONFIRMED (checked all tracked statements in 0001-0008 this
-- session): none create these. If 0002_finance_schema.sql already ran first
-- in the same apply sequence, its identical do-block below will just hit
-- duplicate_object and no-op, which is fine either order.
-- ============================================================================
do $$ begin
  create type public.payment_method as enum (
    'upi','credit_card','debit_card','net_banking','cash','cheque',
    'demand_draft','scholarship','grant','loan','waiver'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_status as enum ('pending','processing','success','failed','refunded');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payout_status as enum ('draft','pending_approval','approved','paid','rejected');
exception when duplicate_object then null; end $$;


-- ============================================================================
-- Schemas
-- ============================================================================
create schema if not exists academic;
create schema if not exists communications;
create schema if not exists audit;


-- ============================================================================
-- Functions (created before tables/triggers that reference them)
-- ============================================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

create or replace function audit.log_change()
returns trigger
language plpgsql
security definer
as $function$
declare
  v_actor_id uuid;
  v_actor_role text;
begin
  begin
    v_actor_id := (auth.jwt() ->> 'sub')::uuid;
    v_actor_role := auth.jwt() -> 'app_metadata' ->> 'role';
  exception when others then
    v_actor_id := null;
    v_actor_role := 'service_role';
  end;

  insert into audit.log (actor_auth_user_id, actor_role, action, entity_schema, entity_table, entity_id, old_data, new_data)
  values (
    v_actor_id,
    coalesce(v_actor_role, 'service_role'),
    TG_OP,
    TG_TABLE_SCHEMA,
    TG_TABLE_NAME,
    coalesce((case when TG_OP = 'DELETE' then old.id else new.id end), null),
    case when TG_OP in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when TG_OP in ('UPDATE','INSERT') then to_jsonb(new) else null end
  );
  return coalesce(new, old);
end;
$function$;


-- ============================================================================
-- 1. public.schools  (root of the whole FK tree — must exist before students/staff)
-- ============================================================================
create table if not exists public.schools (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  created_at  timestamptz not null default now()
);

alter table public.schools enable row level security;

-- NOTE: currently 'authenticated'-wide, same as before this session (not one
-- of the 7 tables in the original security fix scope) — reference/config
-- data, low sensitivity, left as-is. Flagging for your judgment, not changed.
create policy schools_read on public.schools
for select
using (auth.role() = 'authenticated');


-- ============================================================================
-- 2. public.students  (CORRECTED to match live — 0001's tracked version is
--    missing school_id, admission_number, guardian_contact, auth_user_id)
-- ============================================================================
create table if not exists public.students (
  id                 uuid primary key default gen_random_uuid(),
  school_id          uuid not null references public.schools(id) on delete cascade,
  full_name          text not null,
  admission_number   text not null,
  guardian_contact   text,
  created_at         timestamptz not null default now(),
  auth_user_id       uuid references auth.users(id),
  unique (school_id, admission_number)
);

alter table public.students enable row level security;

-- FIXED this session: was using root-level auth.jwt() ->> 'school_id' (claim
-- doesn't exist, always evaluated false, blocked all client-side inserts).
create policy school_isolation_insert_students on public.students
for insert
with check (school_id = (((auth.jwt() -> 'app_metadata'::text) ->> 'school_id'::text))::uuid);

create policy school_isolation_select_students on public.students
for select
using (school_id = (((auth.jwt() -> 'app_metadata'::text) ->> 'school_id'::text))::uuid);


-- ============================================================================
-- 3. public.staff  (CORRECTED to match live — 0001's tracked version is
--    missing school_id, bank_account_last4, monthly_salary, max_periods,
--    auth_user_id)
-- ============================================================================
create table if not exists public.staff (
  id                    uuid primary key default gen_random_uuid(),
  school_id             uuid not null references public.schools(id) on delete cascade,
  full_name             text not null,
  role                  text not null check (role in ('principal','admin','teacher','accountant','other')),
  bank_account_last4    text,
  monthly_salary        numeric(12,2) not null check (monthly_salary >= 0),
  created_at            timestamptz not null default now(),
  max_periods           integer default 20,
  auth_user_id          uuid references auth.users(id)
);

alter table public.staff enable row level security;

create policy school_isolation_select_employees on public.staff
for select
using (school_id = (((auth.jwt() -> 'app_metadata'::text) ->> 'school_id'::text))::uuid);


-- ============================================================================
-- 4. public.parent_links
-- ============================================================================
create table if not exists public.parent_links (
  id                     uuid primary key default gen_random_uuid(),
  parent_auth_user_id    uuid not null references auth.users(id),
  student_id             uuid not null references public.students(id),
  relationship           text not null default 'guardian',
  created_at             timestamptz not null default now(),
  unique (parent_auth_user_id, student_id)
);

alter table public.parent_links enable row level security;

create policy parent_links_self_read on public.parent_links
for select
using (parent_auth_user_id = auth.uid());


-- ============================================================================
-- 5. public.leave_requests  (replaces the dead/orphaned staff.leave_requests
--    from 0004 — this is what's actually live, in public schema)
-- ============================================================================
create table if not exists public.leave_requests (
  id             uuid primary key default gen_random_uuid(),
  staff_id       uuid not null references public.staff(id),
  start_date     date not null,
  end_date       date not null,
  reason         text,
  status         text not null default 'pending' check (status in ('pending','approved','rejected')),
  approved_by    uuid references public.staff(id),
  created_at     timestamptz not null default now(),
  check (end_date >= start_date)
);

alter table public.leave_requests enable row level security;

create policy self_insert_leave_request on public.leave_requests
for insert
with check (staff_id in (select staff.id from staff where staff.auth_user_id = auth.uid()));

create policy leave_requests_read on public.leave_requests
for select
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or staff_id in (select staff.id from staff where staff.auth_user_id = auth.uid())
);

create policy admin_approve_leave_requests on public.leave_requests
for update
using (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']))
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));


-- ============================================================================
-- 6. public.notifications
-- ============================================================================
create table if not exists public.notifications (
  id                       uuid primary key default gen_random_uuid(),
  recipient_staff_id       uuid references public.staff(id),
  recipient_student_id     uuid references public.students(id),
  type                     text not null,
  title                    text not null,
  body                     text,
  read_at                  timestamptz,
  created_at               timestamptz not null default now(),
  check (num_nonnulls(recipient_staff_id, recipient_student_id) = 1)
);

alter table public.notifications enable row level security;

create policy admin_insert_notifications on public.notifications
for insert
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create policy notifications_read on public.notifications
for select
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or recipient_staff_id in (select staff.id from staff where staff.auth_user_id = auth.uid())
  or recipient_student_id in (select students.id from students where students.auth_user_id = auth.uid())
  or recipient_student_id in (select parent_links.student_id from parent_links where parent_links.parent_auth_user_id = auth.uid())
);


-- ============================================================================
-- 7. public.staff_attendance  (currently zero rows live — "not yet in use",
--    per the HR Overview honest-gap note; table shape captured for completeness)
-- ============================================================================
create table if not exists public.staff_attendance (
  id           uuid primary key default gen_random_uuid(),
  staff_id     uuid not null references public.staff(id),
  date         date not null,
  status       text not null check (status in ('present','absent','half_day','on_leave')),
  marked_by    uuid references public.staff(id),
  created_at   timestamptz not null default now(),
  unique (staff_id, date)
);

alter table public.staff_attendance enable row level security;

create policy staff_attendance_read on public.staff_attendance
for select
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or staff_id in (select staff.id from staff where staff.auth_user_id = auth.uid())
);


-- ============================================================================
-- 8. academic.announcements
-- ============================================================================
create table if not exists academic.announcements (
  id                uuid primary key default gen_random_uuid(),
  school_id         uuid not null references public.schools(id),
  class_id          uuid references academic.classes(id),
  author_staff_id   uuid not null references public.staff(id),
  title             text not null,
  body              text not null,
  created_at        timestamptz not null default now(),
  event_date        date
);

alter table academic.announcements enable row level security;

create policy staff_insert_announcements on academic.announcements
for insert
with check (
  author_staff_id in (select staff.id from staff where staff.auth_user_id = auth.uid())
  or ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
);

-- NOTE: broad 'authenticated' read, not one of the 7 tables in the original
-- security-fix scope. Flagging for your judgment: a class-targeted
-- announcement (class_id set) is currently readable outside that class.
-- Left as-is pending your decision.
create policy announcements_read on academic.announcements
for select
using (auth.role() = 'authenticated');


-- ============================================================================
-- 9. academic.assignments  (CORRECTED — was already partially known, full
--    shape + policies here since previous export only covered finance)
-- ============================================================================
create table if not exists academic.assignments (
  id            uuid primary key default gen_random_uuid(),
  class_id      uuid not null references academic.classes(id),
  subject_id    uuid not null references academic.subjects(id),
  teacher_id    uuid not null references public.staff(id),
  title         text not null,
  description   text,
  due_date      date not null,
  created_at    timestamptz not null default now()
);

alter table academic.assignments enable row level security;

create policy teacher_insert_assignments on academic.assignments
for insert
with check (
  teacher_id in (select staff.id from staff where staff.auth_user_id = auth.uid())
  or ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
);

-- FIXED earlier this session (was: auth.role() = 'authenticated')
create policy assignments_read on academic.assignments
for select
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or teacher_id in (select staff.id from staff where staff.auth_user_id = auth.uid())
  or class_id in (
    select t.class_id from scheduling.timetable t
    join staff s on s.id = t.teacher_id
    where s.auth_user_id = auth.uid()
  )
  or class_id in (
    select cr.class_id from academic.class_roster cr
    join students st on st.id = cr.student_id
    where st.auth_user_id = auth.uid()
  )
  or class_id in (
    select cr.class_id from academic.class_roster cr
    join parent_links pl on pl.student_id = cr.student_id
    where pl.parent_auth_user_id = auth.uid()
  )
);


-- ============================================================================
-- 10. academic.grades
-- ============================================================================
create table if not exists academic.grades (
  id               uuid primary key default gen_random_uuid(),
  student_id       uuid not null references public.students(id),
  subject_id       uuid not null references academic.subjects(id),
  term             text not null,
  marks_obtained   numeric not null check (marks_obtained >= 0),
  max_marks        numeric not null check (max_marks > 0),
  entered_by       uuid references public.staff(id),
  created_at       timestamptz not null default now(),
  unique (student_id, subject_id, term)
);

alter table academic.grades enable row level security;

create policy teacher_insert_grades on academic.grades
for insert
with check (
  entered_by in (select staff.id from staff where staff.auth_user_id = auth.uid())
  or ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
);

-- FIXED earlier this session (was: auth.role() = 'authenticated')
create policy grades_read on academic.grades
for select
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or entered_by in (select staff.id from staff where staff.auth_user_id = auth.uid())
  or student_id in (select students.id from students where students.auth_user_id = auth.uid())
  or student_id in (select parent_links.student_id from parent_links where parent_links.parent_auth_user_id = auth.uid())
);

create policy teacher_update_grades on academic.grades
for update
using (
  entered_by in (select staff.id from staff where staff.auth_user_id = auth.uid())
  or ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
);


-- ============================================================================
-- 11. academic.lesson_resources
-- ============================================================================
create table if not exists academic.lesson_resources (
  id            uuid primary key default gen_random_uuid(),
  class_id      uuid not null references academic.classes(id),
  subject_id    uuid references academic.subjects(id),
  teacher_id    uuid not null references public.staff(id),
  title         text not null,
  description   text,
  file_url      text,
  created_at    timestamptz not null default now()
);

alter table academic.lesson_resources enable row level security;

create policy teacher_insert_lesson_resources on academic.lesson_resources
for insert
with check (
  teacher_id in (select staff.id from staff where staff.auth_user_id = auth.uid())
  or ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
);

-- FIXED earlier this session (was: auth.role() = 'authenticated')
create policy lesson_resources_read on academic.lesson_resources
for select
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or teacher_id in (select staff.id from staff where staff.auth_user_id = auth.uid())
  or class_id in (
    select t.class_id from scheduling.timetable t
    join staff s on s.id = t.teacher_id
    where s.auth_user_id = auth.uid()
  )
  or class_id in (
    select cr.class_id from academic.class_roster cr
    join students st on st.id = cr.student_id
    where st.auth_user_id = auth.uid()
  )
  or class_id in (
    select cr.class_id from academic.class_roster cr
    join parent_links pl on pl.student_id = cr.student_id
    where pl.parent_auth_user_id = auth.uid()
  )
);


-- ============================================================================
-- 12. academic.submissions
-- ============================================================================
create table if not exists academic.submissions (
  id              uuid primary key default gen_random_uuid(),
  assignment_id   uuid not null references academic.assignments(id),
  student_id      uuid not null references public.students(id),
  file_url        text,
  status          text not null default 'submitted' check (status in ('submitted','graded')),
  grade           text,
  feedback        text,
  submitted_at    timestamptz not null default now(),
  unique (assignment_id, student_id)
);

alter table academic.submissions enable row level security;

create policy student_insert_submissions on academic.submissions
for insert
with check (student_id in (select students.id from students where students.auth_user_id = auth.uid()));

-- FIXED earlier this session (was: auth.role() = 'authenticated')
create policy submissions_read on academic.submissions
for select
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or exists (
    select 1 from academic.assignments a
    join staff s on s.id = a.teacher_id
    where a.id = submissions.assignment_id and s.auth_user_id = auth.uid()
  )
  or student_id in (select students.id from students where students.auth_user_id = auth.uid())
  or student_id in (select parent_links.student_id from parent_links where parent_links.parent_auth_user_id = auth.uid())
);

create policy teacher_grade_submissions on academic.submissions
for update
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or exists (
    select 1 from academic.assignments a
    join staff s on s.id = a.teacher_id
    where a.id = submissions.assignment_id and s.auth_user_id = auth.uid()
  )
);


-- ============================================================================
-- 13. communications.messages
-- ============================================================================
create table if not exists communications.messages (
  id                       uuid primary key default gen_random_uuid(),
  sender_staff_id          uuid references public.staff(id),
  sender_student_id        uuid references public.students(id),
  recipient_staff_id       uuid references public.staff(id),
  recipient_student_id     uuid references public.students(id),
  body                     text not null,
  read_at                  timestamptz,
  created_at               timestamptz not null default now(),
  check (num_nonnulls(sender_staff_id, sender_student_id) = 1),
  check (num_nonnulls(recipient_staff_id, recipient_student_id) = 1)
);

alter table communications.messages enable row level security;

create policy self_send_messages on communications.messages
for insert
with check (
  (sender_staff_id is not null and sender_staff_id in (select staff.id from staff where staff.auth_user_id = auth.uid()))
  or (sender_student_id is not null and sender_student_id in (select students.id from students where students.auth_user_id = auth.uid()))
);

-- FIXED earlier this session (was: auth.role() = 'authenticated' — meant any
-- logged-in user, any school, could read every private message in the system)
create policy messages_read on communications.messages
for select
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or sender_staff_id in (select id from staff where auth_user_id = auth.uid())
  or recipient_staff_id in (select id from staff where auth_user_id = auth.uid())
  or sender_student_id in (select id from students where auth_user_id = auth.uid())
  or recipient_student_id in (select id from students where auth_user_id = auth.uid())
  or sender_student_id in (select student_id from parent_links where parent_auth_user_id = auth.uid())
  or recipient_student_id in (select student_id from parent_links where parent_auth_user_id = auth.uid())
);


-- ============================================================================
-- 14. audit.log
-- ============================================================================
create table if not exists audit.log (
  id                      uuid primary key default gen_random_uuid(),
  actor_auth_user_id      uuid,
  actor_role              text,
  action                  text not null,
  entity_schema           text not null,
  entity_table            text not null,
  entity_id               uuid,
  old_data                jsonb,
  new_data                jsonb,
  created_at              timestamptz not null default now()
);

alter table audit.log enable row level security;

create policy audit_log_read on audit.log
for select
using (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));
