-- ============================================================================
-- 0019_finance_schema.sql
--
-- REPLACES the 1-line stub that previously read:
--   "-- 0002_finance_schema.stale: removed due to drift with live DB.
--    Finance schema applied separately."
--
-- Generated by reading the LIVE Supabase project (yhcyhwpdgqupylrnkqht) directly
-- via information_schema / pg_catalog on 2026-07-25 — not reconstructed from
-- memory or old zips. This is the real, current shape of the finance schema.
--
-- DEPENDENCIES (assumed already created by 0001_*.sql — verify before running):
--   - Enum types (created in `public` schema): payment_method, payment_status,
--     payout_status. If 0001 doesn't create these, uncomment the CREATE TYPE
--     block below.
--   - public.schools, public.students, public.staff, public.parent_links
--   - Functions: public.set_updated_at(), audit.log_change() (used by triggers
--     below — these already exist live; if 0001 doesn't create them, this
--     migration's trigger statements will fail and need those functions added
--     first).
--
-- NOTE ON RLS POLICIES BELOW: two categories are included —
--   1) Policies that were already correct and unchanged.
--   2) Five SELECT policies (fee_structures, payroll_runs, purchase_orders,
--      vendor_payments, vendors) that were found LIVE-BROKEN this session:
--      they referenced auth.jwt() ->> 'school_id' (a root-level JWT claim that
--      does not exist — school_id only lives inside app_metadata). This made
--      those five SELECTs always evaluate false, silently blocking all
--      client-side reads. This file contains the FIXED versions (already
--      applied live and verified against real data before this export).
-- ============================================================================

create schema if not exists finance;

-- CONFIRMED: checked all tracked statements in 0001-0008 this session — none
-- create these enum types. Not commented out; required for a fresh instance.
do $$ begin
  create type public.payment_method as enum (
    'upi','credit_card','debit_card','net_banking','cash','cheque',
    'demand_draft','scholarship','grant','loan','waiver'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_status as enum (
    'pending','processing','success','failed','refunded'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payout_status as enum (
    'draft','pending_approval','approved','paid','rejected'
  );
exception when duplicate_object then null; end $$;


-- ============================================================================
-- 1. vendors
-- ============================================================================
create table finance.vendors (
  id            uuid primary key default gen_random_uuid(),
  school_id     uuid not null references public.schools(id) on delete cascade,
  name          text not null,
  contact_info  text,
  created_at    timestamptz not null default now(),
  gstin         text
);
create index idx_vendors_school_id on finance.vendors(school_id);

alter table finance.vendors enable row level security;

create policy admin_insert_vendors on finance.vendors
for insert
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

-- FIXED (was broken: root-level auth.jwt() ->> 'school_id' claim doesn't exist)
create policy school_isolation_select_vendors on finance.vendors
for select
using (school_id = (((auth.jwt() -> 'app_metadata'::text) ->> 'school_id'::text))::uuid);


-- ============================================================================
-- 2. fee_structures
-- ============================================================================
create table finance.fee_structures (
  id             uuid primary key default gen_random_uuid(),
  school_id      uuid not null references public.schools(id) on delete cascade,
  name           text not null,
  amount         numeric(12,2) not null check (amount >= 0),
  academic_year  text not null,
  created_at     timestamptz not null default now()
);
create index idx_fee_structures_school_id on finance.fee_structures(school_id);

alter table finance.fee_structures enable row level security;

-- FIXED (was broken: root-level auth.jwt() ->> 'school_id' claim doesn't exist)
create policy school_isolation_select_fee_structures on finance.fee_structures
for select
using (school_id = (((auth.jwt() -> 'app_metadata'::text) ->> 'school_id'::text))::uuid);


-- ============================================================================
-- 3. invoices
-- ============================================================================
create table finance.invoices (
  id                    uuid primary key default gen_random_uuid(),
  student_id            uuid not null references public.students(id) on delete cascade,
  fee_structure_id      uuid not null references finance.fee_structures(id),
  amount_due            numeric(12,2) not null check (amount_due >= 0),
  amount_paid           numeric(12,2) not null default 0 check (amount_paid >= 0),
  due_date              date not null,
  created_at            timestamptz not null default now(),
  gst_rate              numeric default 0 check (gst_rate >= 0),
  gst_amount            numeric default 0 check (gst_amount >= 0),
  invoice_number        text,
  late_fee_applied_at   timestamptz
);
create index idx_invoices_student on finance.invoices(student_id);
create index idx_invoices_fee_structure_id on finance.invoices(fee_structure_id);

alter table finance.invoices enable row level security;

create policy admin_insert_invoices on finance.invoices
for insert
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create policy school_isolation_select_invoices on finance.invoices
for select
using (
  exists (
    select 1 from students s
    where s.id = invoices.student_id
      and s.school_id = (((auth.jwt() -> 'app_metadata'::text) ->> 'school_id'::text))::uuid
  )
);

create policy admin_update_invoices on finance.invoices
for update
using (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']))
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create trigger audit_invoices
after insert or update or delete on finance.invoices
for each row execute function audit.log_change();


-- ============================================================================
-- 4. payments
-- ============================================================================
create table finance.payments (
  id                     uuid primary key default gen_random_uuid(),
  invoice_id             uuid not null references finance.invoices(id) on delete cascade,
  amount                 numeric(12,2) not null check (amount > 0),
  method                 public.payment_method not null,
  status                 public.payment_status not null default 'pending',
  gateway_order_id       text,
  gateway_payment_id     text,
  gateway_signature      text,
  raw_gateway_response   jsonb,
  approved_by            uuid references public.staff(id),
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  reference_number       text
);
create index idx_payments_invoice on finance.payments(invoice_id);
create index idx_payments_status on finance.payments(status);
create index idx_payments_approved_by on finance.payments(approved_by);

alter table finance.payments enable row level security;

-- NOTE: admin_insert_payments was fixed earlier this session (previously missing
-- an INSERT policy entirely — was the root cause of the "Offline Payment Entry"
-- RLS error). Included here already-fixed.
create policy admin_insert_payments on finance.payments
for insert
with check (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  and exists (
    select 1 from finance.invoices i
    join students s on s.id = i.student_id
    where i.id = payments.invoice_id
      and s.school_id = (((auth.jwt() -> 'app_metadata'::text) ->> 'school_id'::text))::uuid
  )
);

create policy school_isolation_select_payments on finance.payments
for select
using (
  exists (
    select 1 from finance.invoices i
    join students s on s.id = i.student_id
    where i.id = payments.invoice_id
      and s.school_id = (((auth.jwt() -> 'app_metadata'::text) ->> 'school_id'::text))::uuid
  )
);

create trigger audit_payments
after insert or update or delete on finance.payments
for each row execute function audit.log_change();

create trigger trg_payments_updated_at
before update on finance.payments
for each row execute function public.set_updated_at();


-- ============================================================================
-- 5. late_fee_rules
-- ============================================================================
create table finance.late_fee_rules (
  id                 uuid primary key default gen_random_uuid(),
  school_id          uuid not null references public.schools(id),
  grace_period_days  integer not null default 0,
  fee_type           text not null check (fee_type = any (array['flat','percentage'])),
  fee_value          numeric not null check (fee_value >= 0),
  created_at         timestamptz not null default now()
);
create index idx_late_fee_rules_school_id on finance.late_fee_rules(school_id);

alter table finance.late_fee_rules enable row level security;

create policy admin_insert_late_fee_rules on finance.late_fee_rules
for insert
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create policy late_fee_rules_read on finance.late_fee_rules
for select
using (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));


-- ============================================================================
-- 6. budgets
-- ============================================================================
create table finance.budgets (
  id              uuid primary key default gen_random_uuid(),
  school_id       uuid not null references public.schools(id),
  category        text not null,
  academic_year   text not null,
  planned_amount  numeric not null check (planned_amount >= 0),
  created_at      timestamptz not null default now(),
  unique (school_id, category, academic_year)
);

alter table finance.budgets enable row level security;

create policy admin_insert_budgets on finance.budgets
for insert
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create policy budgets_read on finance.budgets
for select
using (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));


-- ============================================================================
-- 7. payroll_runs
-- ============================================================================
create table finance.payroll_runs (
  id             uuid primary key default gen_random_uuid(),
  school_id      uuid not null references public.schools(id) on delete cascade,
  employee_id    uuid not null references public.staff(id) on delete cascade,
  pay_period     text not null,
  gross_amount   numeric(12,2) not null check (gross_amount >= 0),
  deductions     numeric(12,2) not null default 0,
  net_amount     numeric(12,2),
  status         public.payout_status not null default 'draft',
  paid_at        timestamptz,
  created_at     timestamptz not null default now(),
  unique (employee_id, pay_period)
);
create index idx_payroll_school on finance.payroll_runs(school_id);

alter table finance.payroll_runs enable row level security;

-- FIXED (was broken: root-level auth.jwt() ->> 'school_id' claim doesn't exist)
create policy school_isolation_select_payroll on finance.payroll_runs
for select
using (school_id = (((auth.jwt() -> 'app_metadata'::text) ->> 'school_id'::text))::uuid);

create policy admin_approve_payroll_runs on finance.payroll_runs
for update
using (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']))
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create trigger audit_payroll_runs
after insert or update or delete on finance.payroll_runs
for each row execute function audit.log_change();


-- ============================================================================
-- 8. purchase_orders
-- ============================================================================
create table finance.purchase_orders (
  id             uuid primary key default gen_random_uuid(),
  school_id      uuid not null references public.schools(id) on delete cascade,
  vendor_id      uuid not null references finance.vendors(id) on delete cascade,
  description    text not null,
  amount         numeric(12,2) not null check (amount >= 0),
  status         public.payout_status not null default 'draft',
  requested_by   uuid references public.staff(id),
  approved_by    uuid references public.staff(id),
  created_at     timestamptz not null default now(),
  category       text
);
create index idx_po_school_id on finance.purchase_orders(school_id);
create index idx_po_vendor on finance.purchase_orders(vendor_id);
create index idx_po_requested_by on finance.purchase_orders(requested_by);
create index idx_po_approved_by on finance.purchase_orders(approved_by);

alter table finance.purchase_orders enable row level security;

create policy admin_insert_purchase_orders on finance.purchase_orders
for insert
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

-- FIXED (was broken: root-level auth.jwt() ->> 'school_id' claim doesn't exist)
create policy school_isolation_select_purchase_orders on finance.purchase_orders
for select
using (school_id = (((auth.jwt() -> 'app_metadata'::text) ->> 'school_id'::text))::uuid);

create policy admin_approve_purchase_orders on finance.purchase_orders
for update
using (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']))
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create trigger audit_purchase_orders
after insert or update or delete on finance.purchase_orders
for each row execute function audit.log_change();


-- ============================================================================
-- 9. vendor_payments
-- ============================================================================
create table finance.vendor_payments (
  id                  uuid primary key default gen_random_uuid(),
  purchase_order_id   uuid not null references finance.purchase_orders(id) on delete cascade,
  amount              numeric(12,2) not null check (amount > 0),
  method              text not null,
  status              public.payout_status not null default 'pending_approval',
  paid_at             timestamptz,
  created_at          timestamptz not null default now(),
  category            text
);
create index idx_vendor_payments_po on finance.vendor_payments(purchase_order_id);

alter table finance.vendor_payments enable row level security;

-- FIXED (was broken: root-level auth.jwt() ->> 'school_id' claim doesn't exist)
create policy school_isolation_select_vendor_payments on finance.vendor_payments
for select
using (
  exists (
    select 1 from finance.purchase_orders po
    where po.id = vendor_payments.purchase_order_id
      and po.school_id = (((auth.jwt() -> 'app_metadata'::text) ->> 'school_id'::text))::uuid
  )
);

create policy admin_approve_vendor_payments on finance.vendor_payments
for update
using (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']))
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create trigger audit_vendor_payments
after insert or update or delete on finance.vendor_payments
for each row execute function audit.log_change();


-- ============================================================================
-- 10. bank_statement_lines
-- ============================================================================
create table finance.bank_statement_lines (
  id                          uuid primary key default gen_random_uuid(),
  statement_date              date not null,
  description                 text not null,
  amount                      numeric not null,
  matched_payment_id          uuid references finance.payments(id),
  matched_vendor_payment_id   uuid references finance.vendor_payments(id),
  status                      text not null default 'unmatched'
                                check (status = any (array['unmatched','matched','ignored'])),
  created_at                  timestamptz not null default now()
);
create index idx_bank_lines_matched_payment_id on finance.bank_statement_lines(matched_payment_id);
create index idx_bank_lines_matched_vendor_payment_id on finance.bank_statement_lines(matched_vendor_payment_id);

alter table finance.bank_statement_lines enable row level security;

create policy admin_insert_bank_lines on finance.bank_statement_lines
for insert
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create policy bank_lines_read on finance.bank_statement_lines
for select
using (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create policy admin_update_bank_lines on finance.bank_statement_lines
for update
using (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']))
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));


-- ============================================================================
-- 11. waiver_requests
-- ============================================================================
create table finance.waiver_requests (
  id                 uuid primary key default gen_random_uuid(),
  student_id         uuid not null references public.students(id),
  invoice_id         uuid references finance.invoices(id),
  request_type       text not null check (request_type = any (array['scholarship','waiver','grant'])),
  requested_amount   numeric not null check (requested_amount > 0),
  reason             text,
  status             text not null default 'pending'
                       check (status = any (array['pending','approved','rejected'])),
  approved_by        uuid references public.staff(id),
  created_at         timestamptz not null default now(),
  disbursed_at       timestamptz
);
create index idx_waivers_student_id on finance.waiver_requests(student_id);
create index idx_waivers_invoice_id on finance.waiver_requests(invoice_id);
create index idx_waivers_approved_by on finance.waiver_requests(approved_by);

alter table finance.waiver_requests enable row level security;

create policy parent_insert_waiver_requests on finance.waiver_requests
for insert
with check (
  student_id in (select parent_links.student_id from parent_links where parent_links.parent_auth_user_id = auth.uid())
  or ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
);

create policy waiver_requests_read on finance.waiver_requests
for select
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or student_id in (select parent_links.student_id from parent_links where parent_links.parent_auth_user_id = auth.uid())
  or student_id in (select students.id from students where students.auth_user_id = auth.uid())
);

create policy admin_decide_waiver_requests on finance.waiver_requests
for update
using (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']))
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));


-- ============================================================================
-- 12. payment_plans
-- ============================================================================
create table finance.payment_plans (
  id                    uuid primary key default gen_random_uuid(),
  invoice_id            uuid not null references finance.invoices(id),
  total_installments     integer not null check (total_installments > 1),
  installment_amount    numeric not null check (installment_amount > 0),
  start_date            date not null,
  status                text not null default 'active'
                          check (status = any (array['active','completed','defaulted','cancelled'])),
  created_at            timestamptz not null default now()
);
create index idx_payment_plans_invoice_id on finance.payment_plans(invoice_id);

alter table finance.payment_plans enable row level security;

create policy admin_insert_payment_plans on finance.payment_plans
for insert
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create policy parent_request_payment_plans on finance.payment_plans
for insert
with check (
  invoice_id in (
    select i.id from finance.invoices i
    join parent_links pl on pl.student_id = i.student_id
    where pl.parent_auth_user_id = auth.uid()
  )
);

create policy payment_plans_read on finance.payment_plans
for select
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or invoice_id in (
    select i.id from finance.invoices i
    where i.student_id in (select students.id from students where students.auth_user_id = auth.uid())
       or i.student_id in (select parent_links.student_id from parent_links where parent_links.parent_auth_user_id = auth.uid())
  )
);


-- ============================================================================
-- 13. payment_plan_installments
-- ============================================================================
create table finance.payment_plan_installments (
  id                   uuid primary key default gen_random_uuid(),
  payment_plan_id      uuid not null references finance.payment_plans(id),
  installment_number   integer not null,
  due_date             date not null,
  amount               numeric not null check (amount > 0),
  status               text not null default 'pending'
                         check (status = any (array['pending','paid','overdue'])),
  payment_id           uuid references finance.payments(id),
  unique (payment_plan_id, installment_number)
);
create index idx_installments_payment_id on finance.payment_plan_installments(payment_id);

alter table finance.payment_plan_installments enable row level security;

create policy admin_insert_installments on finance.payment_plan_installments
for insert
with check (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal']));

create policy installments_read on finance.payment_plan_installments
for select
using (
  ((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) = any (array['admin','principal'])
  or payment_plan_id in (
    select pp.id from finance.payment_plans pp
    join finance.invoices i on i.id = pp.invoice_id
    where i.student_id in (select students.id from students where students.auth_user_id = auth.uid())
       or i.student_id in (select parent_links.student_id from parent_links where parent_links.parent_auth_user_id = auth.uid())
  )
);


-- ============================================================================
-- 14. vendor_performance (VIEW, not a table)
-- ============================================================================
create or replace view finance.vendor_performance as
select
  v.id as vendor_id,
  v.name as vendor_name,
  count(po.id) as total_orders,
  coalesce(sum(po.amount), 0::numeric) as total_order_value,
  count(po.id) filter (where po.status = 'paid'::public.payout_status) as orders_paid,
  count(po.id) filter (where po.status = 'rejected'::public.payout_status) as orders_rejected
from finance.vendors v
left join finance.purchase_orders po on po.vendor_id = v.id
group by v.id, v.name;
